services:

  vector:
    image: timberio/vector:0.27.0-alpine
    ports:
      - 8686:8686
    volumes:
      - ./vector/vector.toml:/etc/vector/vector.toml:ro
      - /var/run/docker.sock:/var/run/docker.sock

  nginx:
    build: ./nginx
    ports:
      - 80:80

  quickwit:
    image: quickwit/quickwit
    volumes:
      - ./quickwit:/quickwit/qwdata
    ports:
      - 7280:7280
    command: run

  pushgateway:
    image: prom/pushgateway
    ports:
      - 9091:9091

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
