global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s
  
scrape_configs:
- job_name: prometheus
  metrics_path: /metrics
  static_configs:
  - targets:
    - localhost:9090

- job_name: pushgateway
  honor_labels: true
  static_configs:
  - targets:
    - pushgateway:9091